name: Deploy
run-name: Deploy ${{ github.ref_name }}

on:
  push:
    tags:
      - v*.*.*

concurrency:
  cancel-in-progress: false
  group: "${{ github.workflow }}-${{ github.ref_name }}"

jobs:
  generate:
    name: Generate
    uses: ./.github/workflows/generate-version.yml
    
  release:
    name: Release
    uses: ./.github/workflows/notify-release.yml
    with:
      tag: v${{ needs.generate.outputs.sem-ver }}
    secrets:
      google-chat-webhook-url: "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
