name: Update PR

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  pull-request:
    name: Pull Request
    uses: ./.github/workflows/update-pull-request.yml
    permissions:
      issues: read
      pull-requests: write
      repository-projects: read
    with:
      environment: Preview
