name: Pull Request Update

on:
  workflow_call:
    inputs:
      environment:
        description: The environment name to inject into the pull request description.
        required: true
        type: string
    outputs:
      description:
        description: The rendered pull request description.
        value: '${{ jobs.update.outputs.description }}'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    outputs:
      description: '${{ steps.update.outputs.description }}'
    steps:
      - name: Update
        id: update
        uses: cupel-co/actions/.github/actions/pull-request/update@f0995465d50036e76ec0d4d7886f33818b710c49
        with:
          environment: ${{ inputs.environment }}
