name: Notify PR opened

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  pull-request:
    name: Pull Request
    uses: ./.github/workflows/pull-request.notify.yml
    permissions:
      issues: read
      pull-requests: read
      repository-projects: read
    secrets:
      google-chat-webhook-url: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
