name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: The tag value
        required: true
        type: string
    secrets:
      google-chat-webhook-url:
        description: The Webhook URL for the chat to send the message to
        required: true
      gpg-key:
        description: The private GPG key used for signing the Git tag.
        required: true
      gpg-password:
        description: The passphrase for the GPG private key.
        required: true
      token:
        description: Token for github interaction
        required: true

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: '${{ secrets.token }}'
      - name: Tag
        uses: cupel-co/actions/.github/actions/github/tag@v0.23.5
        with:
          gpg-key: '${{ secrets.gpg-key }}'
          gpg-password: '${{ secrets.gpg-password }}'
          tag: '${{ inputs.tag }}'

  github:
    name: GitHub
    runs-on: ubuntu-latest
    needs:
      - tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: '${{ secrets.token }}'
      - name: Release
        uses: cupel-co/actions/.github/actions/github/release@v0.23.5
        with:
          tag: '${{ inputs.tag }}'
          token: '${{ secrets.token }}'

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - github
    steps:
      - name: Release
        uses: cupel-co/actions/.github/actions/notify/release@v0.23.5
        with:
          google-chat-webhook-url: '${{ secrets.google-chat-webhook-url }}'
          tag: '${{ inputs.tag }}'
