name: Release Notify

on:
  workflow_call:
    inputs: 
      tag:
        description: The release tag to include in the notification
        required: true
        type: string
    secrets:
      google-chat-webhook-url:
        description: The URL for sending messages to Google Chat
        required: true

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat
        uses: cupel-co/actions/.github/actions/release/notify@052b8f5004d1e4d35ae0e5d0fd263f05d173b62c
        with: 
          google-chat-webhook-url: '${{ secrets.google-chat-webhook-url }}'
          tag: '${{ inputs.tag }}'
