name: Version Generate

on:
  workflow_call:
    inputs:
      flow-type:
        description: 'The flow type to use (GITHUB_FLOW)'
        required: false
        default: GITHUB_FLOW
        type: string
    outputs:
      major:
        description: The Major value
        value: '${{ jobs.generate.outputs.major }}'
      minor:
        description: The Minor value
        value: '${{ jobs.generate.outputs.minor }}'
      patch:
        description: The Patch value
        value: '${{ jobs.generate.outputs.patch }}'
      pre-release-tag:
        description: The prerelease tag value
        value: '${{ jobs.generate.outputs.pre-release-tag }}'
      pre-release-tag-with-dash:
        description: The prerelease tag with dash value
        value: '${{ jobs.generate.outputs.pre-release-tag-with-dash }}'
      pre-release-label:
        description: The prerelease lable value
        value: '${{ jobs.generate.outputs.pre-release-label }}'
      pre-release-number:
        description: The prerelease number value
        value: '${{ jobs.generate.outputs.pre-release-number }}'
      weighted-pre-release-number:
        description: The weighted prerelease number value
        value: '${{ jobs.generate.outputs.weighted-pre-release-number }}'
      build-meta-data:
        description: The build metadata value
        value: '${{ jobs.generate.outputs.build-meta-data }}'
      full-build-meta-data:
        description: The full build metadata value
        value: '${{ jobs.generate.outputs.full-build-meta-data }}'
      major-minor-patch:
        description: The major minor patch value
        value: '${{ jobs.generate.outputs.major-minor-patch }}'
      sem-ver:
        description: The semantic version value
        value: '${{ jobs.generate.outputs.sem-ver }}'
      assembly-sem-ver:
        description: The assembly semantic version value
        value: '${{ jobs.generate.outputs.assembly-sem-ver }}'
      assembly-sem-file-ver:
        description: The file assembly semantic version value
        value: '${{ jobs.generate.outputs.assembly-sem-file-ver }}'
      full-sem-ver:
        description: The full semantic version value
        value: '${{ jobs.generate.outputs.full-sem-ver }}'
      informational-version:
        description: The informational version value
        value: '${{ jobs.generate.outputs.informational-version }}'
      branch-name:
        description: The branch name value
        value: '${{ jobs.generate.outputs.branch-nam }}'
      escaped-branch-name:
        description: The escaped branch name value
        value: '${{ jobs.generate.outputs.escaped-branch-name }}'
      sha:
        description: The sha value
        value: '${{ jobs.generate.outputs.sha }}'
      short-sha:
        description: The short sha value
        value: '${{ jobs.generate.outputs.short-sha }}'
      version-source-sha:
        description: The version source sha value
        value: '${{ jobs.generate.outputs.version-source-sha }}'
      commits-since-version-source:
        description: The commits since version source value
        value: '${{ jobs.generate.outputs.commits-since-version-source }}'
      uncommitted-changes:
        description: The uncommitted changes value
        value: '${{ jobs.generate.outputs.uncommitted-changes }}'
      commit-date:
        description: The commit date value
        value: '${{ jobs.generate.outputs.commit-date }}'

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      major: '${{ steps.generate.outputs.major }}'
      minor: '${{ steps.generate.outputs.minor }}'
      patch: '${{ steps.generate.outputs.patch }}'
      pre-release-tag: '${{ steps.generate.outputs.pre-release-tag }}'
      pre-release-tag-with-dash: '${{ steps.generate.outputs.pre-release-tag-with-dash }}'
      pre-release-label: '${{ steps.generate.outputs.pre-release-label }}'
      pre-release-number: '${{ steps.generate.outputs.pre-release-number }}'
      weighted-pre-release-number: '${{ steps.generate.outputs.weighted-pre-release-number }}'
      build-meta-data: '${{ steps.generate.outputs.build-meta-data }}'
      full-build-meta-data: '${{ steps.generate.outputs.full-build-meta-data }}'
      major-minor-patch: '${{ steps.generate.outputs.major-minor-patch }}'
      sem-ver: '${{ steps.generate.outputs.sem-ver }}'
      assembly-sem-ver: '${{ steps.generate.outputs.assembly-sem-ver }}'
      assembly-sem-file-ver: '${{ steps.generate.outputs.assembly-sem-file-ver }}'
      full-sem-ver: '${{ steps.generate.outputs.full-sem-ver }}'
      informational-version: '${{ steps.generate.outputs.informational-version }}'
      branch-name: '${{ steps.generate.outputs.branch-name }}'
      escaped-branch-name: '${{ steps.generate.outputs.escaped-branch-name }}'
      sha: '${{ steps.generate.outputs.sha }}'
      short-sha: '${{ steps.generate.outputs.short-sha }}'
      version-source-sha: '${{ steps.generate.outputs.version-source-sha }}'
      commits-since-version-source: '${{ steps.generate.outputs.commits-since-version-source }}'
      uncommitted-changes: '${{ steps.generate.outputs.uncommitted-changes }}'
      commit-date: '${{ steps.generate.outputs.commit-date }}'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Generate
        id: generate
        uses: cupel-co/actions/.github/actions/version/generate@v0.25.2
        with: 
          flow-type: '${{ inputs.flow-type }}'
        